spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: postgres
    password: postgres
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
    loadbalancer:
      ribbon:
        enabled: false # Ensure Ribbon is disabled if previously used

eureka:
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true # Fetch registry information
    register-with-eureka: true # Register this service with Eureka
  instance:
    prefer-ip-address: true

server:
  port: 8080
