spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newdb
    username: postgres
    password: postgres
  #    driver-class-name: org.postgresql.Driver
  #  jpa:
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: ecommerce-order-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # Ensure Ribbon is disabled if previously used

eureka:
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka Server
    fetch-registry: true # Fetch registry information
    register-with-eureka: true # Register this service with Eureka
  instance:
    prefer-ip-address: true

server:
  port: 8080

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh
