spring:
  config:
    import:
      - optional:resilience4j-config.yml
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: postgres
    password: postgres
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
    loadbalancer:
      ribbon:
        enabled: false # Ensure Ribbon is disabled if previously used

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 2000     # → Time (ms) to establish TCP connection
        readTimeout: 3000        # → Time (ms) to wait for the response
        loggerLevel: full        # → Log full request & response (useful for debugging)
