resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.net.UnknownHostException
          - java.io.IOException
          - feign.RetryableException
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
    instances:
      productService:
        baseConfig: default
        failureRateThreshold: 40
        subscribeForEvents: true
      inventoryService:
        baseConfig: default
      paymentService:
        baseConfig: default

  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 10s
        retryExceptions:
          - java.io.IOException
          - feign.RetryableException
      inventoryService:
        maxAttempts: 2
        waitDuration: 5s
      paymentService:
        maxAttempts: 4
        waitDuration: 3s
