resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.net.UnknownHostException
          - java.io.IOException
          - feign.RetryableException
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - java.lang.IllegalArgumentException

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 5s
        retryExceptions:
          - java.io.IOException
          - feign.RetryableException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        subscribeToEvents: true  # 👈 ensures event listeners (like logs) work
