resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10           # Increased from 5 to 10 for better stability
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s    # Increased from 10s to 30s to give more recovery time
        permittedNumberOfCallsInHalfOpenState: 3 # Increased from 2 to 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - feign.RetryableException
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
    instances:
      productService:
        baseConfig: default
        failureRateThreshold: 40
        subscribeWithEventConsumer: true        # More strict threshold for product service
      inventoryService:
        baseConfig: default
      paymentService:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.io.IOException
          - feign.RetryableException
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:  # Don't retry on these
          - javax.validation.ValidationException
    instances:
      productService:
        baseConfig: default
        waitDuration: 2s               # Longer wait for product service
      inventoryService:
        baseConfig: default
      paymentService:
        baseConfig: default

  # Add this to enable event publishing for logging
