resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.net.UnknownHostException
          - java.io.IOException
          - feign.RetryableException
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - com.ecommerce.orderservice.exception.NonRetryableBusinessException
    instances:
      productService:
        baseConfig: default
        failureRateThreshold: 40
        subscribeWithEventConsumer: true
      inventoryService:
        baseConfig: default
      paymentService:
        baseConfig: default

  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 5s
        retryExceptions:
          - java.io.IOException
          - feign.RetryableException
      productService:
        baseConfig: default
      inventoryService:
        baseConfig: default
