spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres

eureka:
  instance:
    hostname: ecommerce-inventory-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9093
