spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: postgres
    password: postgres
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # Ensure Ribbon is disabled if previously used
    config:
      uri: http://localhost:8888 # URL of the Config Server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8080
