spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres

eureka:
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true # Fetch registry information
    register-with-eureka: true # Register this service with Eureka
  instance:
    prefer-ip-address: true
